services:
  image-creater-dbot:
    image: python:3.11.10-bookworm
    container_name: image-creater-dbot
    build:
      context: .
      dockerfile: Dockerfile
    env_file: 
      - .env
    volumes:
      - ./:/usr/app # ホスト側のパス:コンテナ側の絶対パス